import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import layoutStyles from './layout.module.css'

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            
            
             <div className={layoutStyles.body}>
                <div className={layoutStyles.contentContainer}>
                    <header className={layoutStyles.header}>
                        <div className={layoutStyles.banner}>
                            <p className={layoutStyles.bannerEntry}>
                                <Link href='/'>Home</Link>
                            </p>
                            <p className={layoutStyles.bannerEntry}>
                                <Link href='/about'>About</Link>
                            </p>
                            <p className={layoutStyles.bannerEntry}>
                                <Link href='/favAlbums'>Favorite Albums</Link>
                            </p>
                            <p className={layoutStyles.bannerEntry}>
                                <Link href='/recentAlbums'>Recent Albums</Link>
                            </p>
                            <p className={layoutStyles.bannerEntry}>
                                <Link href='/albumLists'>Album Lists</Link>
                            </p>
                        </div>
                    </header>

                    <div className={layoutStyles.mainContainer}>
                        {children}
                    </div>

                </div>
            </div> 
        </>
    )
}